{% extends "layouts/app.phtml" %}

{% block header_title %} Pingaroo {% endblock %}
{% block body_title %} Ping List {% endblock %}
 
{% block content %} 
<a href="{{ url('batch/new') }}"><button type="button" class="btn btn-sm btn-primary">New Batch</button></a>
<br />
<br /> 

{{ partial('common/partials/confirmModelDelete') }}

<div class="row">
    <form action="{{ url('ping') }}" method="GET">
        <div class="col-xs-3"> 
            Proxy
            <br />
            <select name="proxyId[]" class="form-control" multiple="multiple">
                {% for proxy in proxies %}
                    <option value="{{ proxy.id }}"<?php
                        if(in_array($proxy->id, $reflected_proxyId)) {
                            echo 'selected="selected"';
                        }
                    ?>>{{ proxy.address }}</option>    
                {% endfor %}
            <select>
        </div>
        <div class="col-xs-3">
            URL
            <br />
            <select name="urlId[]" class="form-control" multiple="multiple">
                {% for urlValue in urls %}
                    <option value="{{ urlValue.id }}"<?php
                        if(in_array($urlValue->id, $reflected_urlId)) {
                            echo 'selected="selected"';
                        }
                    ?>>{{ urlValue.address }}</option>
                {% endfor %}
            <select>
        </div>
        <div class="col-xs-3">
            Batch
            <br />
            <select name="batchId" class="form-control">
                <option value="-1">-- All Batches --</option>
                {% for batch in batches %}
                    <option value="{{ batch.id }}"
                        {% if batch.id == reflected_batchId %}
                            selected="selected"
                        {% endif %}
                    >{{ batch.id ~ ' - ' ~ batch.name }} </option>
                {% endfor %}
            <select>
        </div>        
        <div class="col-xs-3">
            <br />
            <input type="submit" class="form-control" value="search">
        </div>
    </form>
        
    <div style="clear:both"></div>
    <br />
    
    <div class="col-xs-12">
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
            <table id="pingTable" class="table table-hover">
                <thead>
                    <th>ID</th>
                    <th>Proxy</th>
                    <th>Url</th>
                    <th>Actions</th>
                </thead>
                <tbody>                    
                    {% for ping in pings %}
                        <tr>
                            <td>{{ ping.id }}</td>
                            <td>{{ ping.proxyAddress }} 
                            </td>
                            <td>{{ ping.urlAddress }}
                            </td>
                            <td>
                                <a href="{{ url('ping/search/' ~ ping.id) }}">
                                    <button type="button" class="btn btn-sm btn-default">Show</button>
                                </a>
                                <a href="{{ url('batch?id=' ~ ping.batchId) }}">
                                    <button type="button" class="btn btn-sm btn-primary">Go to Batch</button>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
$(document).ready(function(){
    $('#pingTable').dataTable();
});
</script>
     
{% endblock %}

{% block bottom %}
{% endblock %}